/**
 * Types for the embedding atlas.
 *
 * The actual data lives in lib/embeddings.json, generated by
 * scripts/generate-embeddings.mjs at build time. No vectors are included —
 * all similarity math runs in the build script; the browser receives 2D coords
 * and precomputed nearest-neighbour indices only.
 *
 * HARD CONSTRAINT: @huggingface/transformers must never be imported here or
 * in any client component. This file exports pure types + the static JSON.
 */

export type EmbeddingKind = "post-para" | "work" | "about"

export interface EmbeddingEntry {
  /** Stable identifier for React keys. */
  id: string
  /** Source category. */
  kind: EmbeddingKind
  /** Navigation target — absolute path or anchor. */
  href: string
  /** Short excerpt shown in the hover card (≤180 chars). */
  excerpt: string
  /** PCA x-coordinate, normalised to [0, 1]. */
  x: number
  /** PCA y-coordinate, normalised to [0, 1]. */
  y: number
  /** Indices of the 3 nearest neighbours in the flat entries array. */
  neighbors: [number, number, number]
}
